name: Scedule test
on: 
  schedule:
    - cron '*/2 * * * *'
jobs:
  my-job:
    name: cron echo commands
    runs-on: ubuntu-latest
    steps:
    - name: cron  greeting
      run: |
        echo 'hello World'.